### ISSUE TITLE
You forgot to publish your newest commits to PyPI

### ISSUE THREAD

**Issue by spgill** [kepoorhampond/python-draftlog#6]
Just wanted to let you know, because the relative import bugs are still there on pypi. 😌

**Comment by cooperhammond** [comment]
Thanks, I often forget to do this. Is there a way to automate it in a good way that you know of?

**Comment by spgill** [comment]
If by automate, you mean auto-magically upload to pypi everytime you commit to GitHub; I'm not entirely sure that's possible. But for just uploading to pypi, I find the `twine` package/utility to be the easiest to use. You basically just have to run `twine upload dist/*` after building the distribution tarball.

**Comment by cooperhammond** [comment]
Hmm, maybe just an automation script on a raspberry pi checking the `master` branch, or something like that. Thanks though!
